### ISSUE TITLE
Please add minisatip build with dvbapi support

### ISSUE THREAD

**Issue by SmoothMC** [Jalle19/satip-axe#12]
Hey Jalle19,

thanks for this update version of satip-axe it runs really stable on my ggs.box
but the new Version of minisatip in your build doesn't have the dvbaip feature enabled.
can u please add this soon

thanks for support

**Comment by Jalle19** [comment]
As far as I know, DVBAPI support is disabled because the device doesn't have enough CPU resources to decrypt channels.

I can create a test firmware for you if you want to try?

**Comment by SmoothMC** [comment]
this would be very nice is there a way that you use the latest release of minisatip then?
At the moment i use "minisatip 1.1.43" with your firmware, but i not get it to built it by my self

thx

**Comment by Jalle19** [comment]
Sure

**Comment by Jalle19** [comment]
I made a test build with DVB-CSA support, see the pull request
