### ISSUE TITLE
Change update-fw script to point to this fork

### ISSUE THREAD

**Issue by pejesat** [Jalle19/satip-axe#21]
Hi, I've running satip axe (think it's v 14) on internal flash on digibit r1.
Is it save to change just the link inside upgrade-fw and then upgrade to your new version?
Thanks a lot for your work
cu peje

**Comment by Jalle19** [comment]
I haven't used the `upgrade-fw` script personally, I'll have to check it out. I would suggest flashing it from USB like the README explains.

**Comment by Jalle19** [comment]
See https://github.com/Jalle19/satip-axe/pull/22

**Comment by Jalle19** [comment]
Too much work too keep this script maintained, you'll have to flash using a USB stick from now on.
