### ISSUE TITLE
Any chance to watch dB values with minisatip (satip-axe) for Digibit R1?

### ISSUE THREAD

**Issue by roisiano** [Jalle19/satip-axe#33]
Hello:

Is possible or could it be to watch dB values in status "web" of minisatip?
Dibibit R1 IP:8080

Where there is information about Signal,
example:
STR: 94%
SNR: 71%

Could I see dB values?

Currently using build 22.

Kind regards

**Comment by Jalle19** [comment]
As far as I know it's not possible to get the decibel value from the drivers :shrug:

**Comment by roisiano** [comment]
> As far as I know it's not possible to get the decibel value from the drivers 🤷

It's a pitty. Anyway, thanks for the reply and for the new versions.

Kind regards
