### ISSUE TITLE
Digibit does not start anymore

### ISSUE THREAD

**Issue by fir3drag0n** [Jalle19/satip-axe#34]
Hi,

i just wanted to use your newest build22, but when I push the new unicable setting to the box, it does not start anymore:

I have a unicable setup and I tried to use this settings:

`MINISATIP="yes"`
`MINISATIP_OPTS="-A 0:1-1210,1:0-1420,2:2-1680,3:3-2040"`

Any help is appreciated!

**Comment by ClashC** [comment]
On my grundig box I could not start Unicable either. Started manually, no stations could be tuned on the client… Due to lack of time I could not test further until now... and I am also very interested in a solution. :)

**Comment by Jalle19** [comment]
Try adding `-Z *:0` to the options, and try to tune a channel a second time if it fails the first time.

**Comment by fir3drag0n** [comment]
Like this?

MINISATIP_OPTS="-A -Z *:0 0:1-1210,1:0-1420,2:2-1680,3:3-2040

**Comment by Jalle19** [comment]
No, before `-A`

**Comment by fir3drag0n** [comment]
This does not work either, no channel is tuned

**Comment by Jalle19** [comment]
Did it work in previous builds?

**Comment by Jalle19** [comment]
Actually you're using the wrong switch, you're supposed to use `-u` or `-j` for Unicable settings, not `-A`. The changes mentioned in the README where for the `-U` switch only (capital U).

I'm sure it'll work once you switch to `-u` or `-j` :+1:
