### ISSUE TITLE
Possible to have tvheadend running directly on device

### ISSUE THREAD

**Issue by rajkosto** [Jalle19/satip-axe#38]
I have to use a raspberry pi next this receiver to run tvheadend on (because the clients do not like the minisatip urls that have ? in them)
Since the original repo had some tvheadend mentions/support, why was this removed ? Did it never compile to begin with ?

**Comment by Jalle19** [comment]
I didn't want to maintain it, it was fairly limited anyway. You'll get a much better experience and performance by running tvheadend on a separate device.
