### ISSUE TITLE
At all possible to do HDHomeRun emulation?

### ISSUE THREAD

**Issue by user897943** [Jalle19/satip-axe#57]
The Plex DVR will accept HDHomeRun devices and nothing else. So instead of using TVHeadend, the channels could come directly from the Digibit R1 if only this firmware could work to emulate a HDHomeRun so that it would expose itself as such to Plex and work without anything in between... Currently I have to use a cumbersome and buggy way> use docker tvheadend then export the playlist to iptv4plex (https://github.com/vorghahn/iptv4plex) then export that playlist to plex dvr, along with xmltv of the same... It always crashes so Plex loses the tuner and channels. If you could do the HDHR emulation in firmware running on the Digibit R1 that would probably resolve all issues. Thanks.

**Comment by Jalle19** [comment]
Sorry, that's out of the scope for this project. You could probably make your own M3U playlist containing HTTP URLs to each channel directly from minisatip.
