### ISSUE TITLE
energy saving

### ISSUE THREAD

**Issue by Lip90** [Jalle19/satip-axe#62]
What are the best energy saving settings? I have two satellite cables connected which come from a multiswitch. The question may seem silly but somehow I do not understand the documentary.

**Comment by Jalle19** [comment]
You don't need to do anything special, the tuners will be powered down after some time of inactivity.

**Comment by Lip90** [comment]
I thought you have to deposit such a parameter? is not necessary?
`#
# minisatip 1.0+
#
MINISATIP="yes"
MINISATIP_OPTS="-W 0"
`

**Comment by Jalle19** [comment]
I'm not entirely sure, I haven't used -W personally at least

**Comment by Lip90** [comment]
I got the documentation from [here](https://github.com/perexg/satip-axe/blob/master/dist/minisatip.md). But I'm not sure if I understood it correctly. I thought without these paramenter a standby is not possible?

**Comment by Jalle19** [comment]
The tuners will power down regardless of which -W mode you use.
