### ISSUE TITLE
/sbin/upgrade-fw: line 64: nandwrite2: not found

### ISSUE THREAD

**Issue by phaze75** [Jalle19/satip-axe#63]
Hi @Jalle19,

I tried to run the upgrade-fw script with your latest firmware build 24, but I have gotten following error: "/sbin/upgrade-fw: line 64: nandwrite2: not found". I checked all my directories, but there is no "nandwrite2". But there is a "/usr/sbin/nandwrite" which is a symbolic link to "/bin/busybox". I googled and found out that "nandwrite" is a "busybox" command. So, I guess simply changing line 64 from "nandwrite2" to "nandwrite" will do the trick. But before I brick my sat box, I wanted to verify the issue and confirm the change with you, just to be on the safe side.

Best regards!

**Comment by Jalle19** [comment]
What build are you trying to upgrade from?

**Comment by phaze75** [comment]
From SATIP-AXE server 202111261231-19.

Sent from my iPhone

On 21.04.2023, at 18:15, Sam Stenvall ***@***.***> wrote:

﻿

What build are you trying to upgrade from?

**Comment by Jalle19** [comment]
That firmware is unfortunately too old to support upgrading with `upgrade-fw`, you need to flash it with a USB drive.

**Comment by phaze75** [comment]
Ok, thanks for clarifying this!

Sent from my iPhone

On 21.04.2023, at 21:05, Sam Stenvall ***@***.***> wrote:

﻿

That firmware is unfortunately too old to support upgrading with upgrade-fw, you need to flash it with a USB drive.
