### ISSUE TITLE
First tune fail

### ISSUE THREAD

**Issue by estimadarocha** [Jalle19/satip-axe#68]
Hi @Jalle19.

Could you try to give me some hints... I am using my digibit with a Jess unicable 2 from inverto. The Jess options seens to be just fine cause i can tune in all FE. Now the problem is that first tune always fails. I am testing this directly with wget calling the stream.

Thanks

**Comment by Jalle19** [comment]
I have the same issue, I think it can be resolved by using a power injector to power the LNB. There's some bug in minisatip that causes the first tune to fail because the LNB is not yet powered on.
