### ISSUE TITLE
How to reboot to satip?

### ISSUE THREAD

**Issue by sakos** [Jalle19/satip-axe#71]
Hello,

I bought a Digibit R1 and have issues.

I could install minisatip on an USB and it works after power cycle the box. However if I reboot the box via linux then it start with the original fw. I need to power cycle the box again to start minisatip.

- Is there a reboot method in SSH that recovers with minisatip?
- is there a recommended way to restart minisatip process only (to modifiy parameters)?
- how can I enable and access debug logs?

**Comment by Jalle19** [comment]
> * Is there a reboot method in SSH that recovers with minisatip?

I would suggest flashing the firmware if you intend to be able to reboot without ending up in the original firmware

> is there a recommended way to restart minisatip process only (to modifiy parameters)?

Yes, just kill the process and the startup script will restart minisatip (with the new parameters, if you've changed them) after a few seconds.

> how can I enable and access debug logs?

If you write `logread` you'll get all the logs. minisatip only logs stuff if you tell it to with the `-l` and `-v` options.
