### ISSUE TITLE
scp does not work anymore

### ISSUE THREAD

**Issue by MusterGit** [Jalle19/satip-axe#77]
At least since rc1. I'm getting this error:
```
/usr/libexec/sftp-server: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
scp: Connection closed
```

Already mentioned [here](https://github.com/Jalle19/satip-axe/issues/75#issuecomment-1614225760)

**Comment by Jalle19** [comment]
Seems like `scp` works but not SFTP. Both should work so this is indeed a bug.

**Comment by Jalle19** [comment]
This is fixed in build25-rc3
