### ISSUE TITLE
Networking issue

### ISSUE THREAD

**Issue by stauraum** [Jalle19/satip-axe#82]
Yesterday I changed from DHCP to static IP.

But because DNS did not work, I added my DNS server as option IPV4_NAMESERVER in the config. Of course I rebooted to check the setting.

Now my Digibit R1 is no longer accessible. 

Unfortunately, flashing the firmware again and a factory reset did not help. What options do I have now?

**Comment by Jalle19** [comment]
Follow the instructions under "Recovery from the wrong configuration" in https://github.com/perexg/satip-axe/blob/master/dist/README

Not sure why your device no longer boots properly though, I haven't tried using static IP myself.

**Comment by stauraum** [comment]
This solved my issue. Thanks a lot.
