### ISSUE TITLE
Tuner disabled

### ISSUE THREAD

**Issue by VenimK** [Jalle19/satip-axe#84]
Had a powersurge.

Got my dgibit R1 back up and running
but my tuners keep getting 'disabled'

> Linux version 2.6.32.42_stm24_0208-idl4k_7108 (root@5e9872285089) (gcc version 4.8.4 20141219 (STMicroelectronics/Linux Base 4.8.4-139) (GCC) ) #1 PREEMPT Sun Aug 6 11:05:32 UTC 2023
Boot params:
... MOUNT_ROOT_RDONLY - 00000001
... RAMDISK_FLAGS     - 00000000
... ORIG_ROOT_DEV     - 00000200
... LOADER_TYPE       - 00000000
... INITRD_START      - 00000000
... INITRD_SIZE       - 00000000
Booting machvec: idl4k
Node 0: start_pfn = 0x70000, low = 0x8f000
Zone PFN ranges:
  Normal   0x00070000 -> 0x0008f000
Movable zone start PFN for each node
early_node_map[1] active PFN ranges
    0: 0x00070000 -> 0x0008f000
On node 0 totalpages: 126976
free_area_init_node: node 0, pgdat 813fd7dc, node_mem_map 82ac3000
  Normal zone: 992 pages used for memmap
  Normal zone: 0 pages reserved
  Normal zone: 125984 pages, LIFO batch:31
Inverto idl4k board initialisation
STx7108 version 2.x, HOST core
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 125984
Kernel command line:  console= hw=16001000000000000000000000000000 sn=1S81T51717001207 uuid=6BF3D2EE4EBF4B0E9CB6DE7C97021AFA revBoot=stm24_0056-idl4k console=ttyAS0,115200 bigphysarea=20000
bpa2: partition 'bigphysarea' created at 0x72ea7000, size 80000 kB (0x04e20000 B)
PID hash table entries: 2048 (order: 1, 8192 bytes)
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
PVR=04909300 CVR=60880000 PRR=0000a320
I-cache : n_ways=2 n_sets=512 way_incr=16384
I-cache : entry_mask=0x00003fe0 alias_mask=0x00003000 n_aliases=4
D-cache : n_ways=2 n_sets=512 way_incr=16384
D-cache : entry_mask=0x00003fe0 alias_mask=0x00003000 n_aliases=4
Memory: 379520k/507904k available (2998k kernel code, 1088k data, 22188k init)
Hierarchical RCU implementation.
NR_IRQS:500
Failed to enable clk CLKA0_REF, ignoring
Failed to enable clk CLKA0_PLL0LS, ignoring
Failed to enable clk CLKA1_REF, ignoring
Failed to enable clk CLKA1_PLL0LS, ignoring
Console: colour dummy device 80x25
console [ttyAS0] enabled
sh_tmu: TMU0 used for clock events
sh_tmu: TMU0 used for periodic clock events
sh_tmu: TMU1 used as clock source
Calibrating delay loop... 595.96 BogoMIPS (lpj=297984)
Mount-cache hash table entries: 512
CPU: STx7108
NET: Registered protocol family 16
bio: create slab <bio-0> at 0
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
Switching to clocksource TMU1
NET: Registered protocol family 2
IP route cache hash table entries: 4096 (order: 2, 16384 bytes)
TCP established hash table entries: 16384 (order: 5, 131072 bytes)
TCP bind hash table entries: 16384 (order: 4, 65536 bytes)
TCP: Hash tables configured (established 16384 bind 16384)
TCP reno registered
NET: Registered protocol family 1
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
[STM]: [PM]: HoM support registered
[STM]: [PM]: [HoM]: Early console @ 0xfd733000
Slow work thread pool: Starting up
Slow work thread pool: Ready
JFFS2 version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
fuse init (API version 7.13)
msgmni has been set to 741
alg: No test for stdrng (krng)
io scheduler noop registered
io scheduler anticipatory registered (default)
io scheduler deadline registered
io scheduler cfq registered
STMicroelectronics ASC driver initialized
stm-asc.0: ttyAS0 at MMIO 0xfd733000 (irq = 108) is a stm-asc
brd: module loaded
NAND device: Manufacturer ID: 0x2c, Chip ID: 0xf1 (Micron NAND 128MiB 3,3V 8-bit)
Bad block table found at page 65472, version 0x01
Bad block table found at page 65408, version 0x01
cmdlinepart partition parsing not available
Creating 5 MTD partitions on "stm-nand-flex.0":
0x000000000000-0x000000020000 : "nand-env"
0x000000020000-0x000000420000 : "nand-system"
0x000000420000-0x000002420000 : "nand-fw1"
0x000002420000-0x000004420000 : "nand-fw2"
0x000004420000-0x000008000000 : "nand-data"
stmmac - user ID: 0x10, Synopsys ID: 0x33
 No HW DMA feature register supported
 Enhanced/Alternate descriptors
 RX Checksum Offload Engine supported
 TX Checksum insertion supported
 Wake-Up On Lan supported
STMMAC MII Bus: probed
eth0: PHY ID 001cc915 at 0 IRQ 0 (1:00)
eth0: PHY ID 001cc915 at 1 IRQ 25 (1:01) active
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
stm_usb_probe: usb_phy_clk clock not found for stm-usb.0
stm-ehci stm-ehci.0: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.0: new USB bus registered, assigned bus number 1
stm-ehci stm-ehci.0: irq 124, io mem 0xfe0ffe00
stm-ehci stm-ehci.0: USB 0.0 started, EHCI 1.00
usb usb1: configuration #1 chosen from 1 choice
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
stm-ohci stm-ohci.0: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.0: new USB bus registered, assigned bus number 2
stm-ohci stm-ohci.0: irq 127, io mem 0xfe0ffc00
usb usb2: configuration #1 chosen from 1 choice
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 1 port detected
stm_usb_probe: usb_phy_clk clock not found for stm-usb.1
stm-ehci stm-ehci.1: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.1: new USB bus registered, assigned bus number 3
stm-ehci stm-ehci.1: irq 125, io mem 0xfe1ffe00
stm-ehci stm-ehci.1: USB 0.0 started, EHCI 1.00
usb usb3: configuration #1 chosen from 1 choice
hub 3-0:1.0: USB hub found
hub 3-0:1.0: 1 port detected
stm-ohci stm-ohci.1: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.1: new USB bus registered, assigned bus number 4
stm-ohci stm-ohci.1: irq 128, io mem 0xfe1ffc00
usb usb4: configuration #1 chosen from 1 choice
hub 4-0:1.0: USB hub found
hub 4-0:1.0: 1 port detected
stm_usb_probe: usb_phy_clk clock not found for stm-usb.2
stm-ehci stm-ehci.2: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.2: new USB bus registered, assigned bus number 5
stm-ehci stm-ehci.2: irq 126, io mem 0xfe2ffe00
stm-ehci stm-ehci.2: USB 0.0 started, EHCI 1.00
usb usb5: configuration #1 chosen from 1 choice
hub 5-0:1.0: USB hub found
hub 5-0:1.0: 1 port detected
stm-ohci stm-ohci.2: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.2: new USB bus registered, assigned bus number 6
stm-ohci stm-ohci.2: irq 129, io mem 0xfe2ffc00
usb usb6: configuration #1 chosen from 1 choice
hub 6-0:1.0: USB hub found
hub 6-0:1.0: 1 port detected
Initializing USB Mass Storage driver...
usbcore: registered new interface driver usb-storage
USB Mass Storage support registered.
usbcore: registered new interface driver usbserial
USB Serial support registered for generic
usbcore: registered new interface driver usbserial_generic
usbserial: USB Serial Driver core
i2c /dev entries driver
stm i2c clock = 100500000, ns_per_clk = 9
stm i2c modified clock = 50250000, ns_per_clk = 19
stm i2c clock = 100500000, ns_per_clk = 9
stm i2c modified clock = 50250000, ns_per_clk = 19
at24 1-0050: 8192 byte 24c64 EEPROM (writable)
sh_tmu: TMU0 kept as earlytimer
sh_tmu: TMU1 kept as earlytimer
STMicroelectronics - Coprocessors st231 Init
st-coprocessor-0: No RAM reserved
st231.0 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
st-coprocessor-1: No RAM reserved
st231.1 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
st-coprocessor-2: No RAM reserved
st231.2 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
TCP cubic registered
NET: Registered protocol family 10
IPv6 over IPv4 tunneling driver
NET: Registered protocol family 17
802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
All bugs added by David S. Miller <davem@redhat.com>
[STM]: [PM]: Suspend support registered
drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
Freeing unused kernel memory: 22188k freed
stapi_core: module license 'ST Microelectronics' taints kernel.
Disabling lock debugging due to kernel taint
Load module sttbx_early_core
Load module stos_core [?]		by insmod (pid 462)
Load module stcommon_core [?]		by insmod (pid 462)
Load module sttbx_core [?]		by insmod (pid 462)
Load module stevt_core [?]		by insmod (pid 462)
Load module stavmem_core [?]		by insmod (pid 462)
Load module stbuffer_core [?]		by insmod (pid 462)
Load module stclock_core [252]		by insmod (pid 462)
Load module stpower_core [251]		by insmod (pid 462)
Load module stpio_core [?]		by insmod (pid 462)
Load module stfdma_core [250]		by insmod (pid 462)
Load module stinject_core [?]		by insmod (pid 462)
Load module stnet_core [?]		by insmod (pid 462)
Load module stpti5_core [?]		by insmod (pid 462)
Load module stcommon_ioctl [249]	by insmod (pid 468)
Load module sttbx_ioctl [248]		by insmod (pid 468)
Load module stevt_ioctl [247]		by insmod (pid 468)
Load module stavmem_ioctl [246]		by insmod (pid 468)
Load module stbuffer_ioctl [245]	by insmod (pid 468)
Load module stpower_ioctl [244]		by insmod (pid 468)
Load module stpio_ioctl [243]		by insmod (pid 468)
Load module stfdma_ioctl [240]		by insmod (pid 468)
Load module stinject_ioctl [239]	by insmod (pid 468)
Load module stnet_ioctl [238]		by insmod (pid 468)
Load module stsys_ioctl [237]		by insmod (pid 468)
Load module stpti5_ioctl [236]		by insmod (pid 468)
I2C-Bus AXE mangle module loaded
[demod900] setup [num_demods 4]
[pll6120] setup [num_plls:4] [clk:30000000] [bbgain:16]
[fe] Checking lut 0xC1AD064C
[fe] Checking lut 0xC1AD0682
[fe] Checking lut 0xC1AD064C
[fe] Checking lut 0xC1AD06B0
[dmx] ... init 0
[fta_fe] FE Initialization done, res 0
[dmx-ts] ... init 0
USB Serial support registered for cp210x
usbcore: registered new interface driver cp210x
cp210x: v0.09:Silicon Labs CP210x RS232 serial adaptor driver
USB Serial support registered for pl2303
usbcore: registered new interface driver pl2303
pl2303: Prolific PL2303 USB to serial adaptor driver
USB Serial support registered for FTDI USB Serial Device
usbcore: registered new interface driver ftdi_sio
ftdi_sio: v1.5.0:USB FTDI Serial Converters Driver
eth0: device MAC address 00:24:a6:00:26:c5
STMMAC MII Bus: Can't get IRQ 25 (PHY)
 No MAC Management Counters available
PHY: 1:01 - Link is Up - 1000/Full
PHY: 1:01 - Link is Down
eth0: no IPv6 routers present
PHY: 1:01 - Link is Up - 1000/Full
PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full

>Apr 20 04:22:36 (none) user.notice minisatip: Setting diseqc timing for adapter -1 before cmd 155 after cmd 54 after repeated cmd 15 after switch 15 after burst 15 after tone 0
Apr 20 04:22:36 (none) daemon.notice minisatip[1488]: minisatip version 1.2.12, compiled in Aug  6 2023 11:00:41, with s2api version: 0501
Apr 20 04:22:36 (none) daemon.notice minisatip[1488]: Initializing with 4 devices

cat /etc/sysconfig/config
#
# SATIP AXE firmware configuration
#

CFGVER="15"
HOSTNAME="satip-axe"
KMODULES="drivers/usb/serial/cp210x.ko drivers/usb/serial/pl2303.ko drivers/usb/serial/ftdi_sio.ko"

#
# STV6210 baseband amplifier gain (0dB .. 16dB - 2dB step)
#
STV6210_BAMP="16dB"
#DEMUXTS_OLD="yes"

#
# ttyUSB names
#

TTYUSB1_DEV="2-1:1.0"
TTYUSB1_NAME="ttyUSBupper"
TTYUSB2_DEV="4-1:1.0"
TTYUSB2_NAME="ttyUSBlower"

TTYUSB3_DEV="1-1.1:1.0"         # USB hub port#1 in upper port
TTYUSB3_NAME="ttyUSBupper1"
TTYUSB4_DEV="3-1.2:1.0"         # USB hub port#2 in lower port
TTYUSB4_NAME="ttyUSBlower2"

#
# IPV4 config
#
IPV4="dhcp"
# or
#IPV4="192.168.1.10"
#IPV4_NETMASK="255.255.255.0"
#IPV4_BROADCAST="192.168.1.255"
#IPV4_GATEWAY="192.168.1.1"

#
# syslogd
#
#SYSLOGD_OPTS="-R 192.168.1.1:514"

#
# telnetd
#
TELNETD="yes"

#
# dropbear
#
DROPBEAR="yes"

#
# minisatip
#
MINISATIP="yes"
MINISATIP_OPTS="-f --diseqc-timing *:155-54-15-15-15-0 -7 0:1,0:2,0:3"

#
# inetd (httpd,ftpd)
#
INETD="yes"

#
# crond
#
CROND="yes"

#
# oscamd
#
OSCAMD="yes"

Any Problems here
or any tips what I can check

**Comment by Jalle19** [comment]
What do you mean by "disabled"?

**Comment by VenimK** [comment]
<img width="2039" alt="Scherm­afbeelding 2024-04-21 om 04 10 41" src="https://github.com/Jalle19/satip-axe/assets/666520/b61c1924-310d-4819-b748-824aa0116567">
<img width="1831" alt="Scherm­afbeelding 2024-04-21 om 04 10 50" src="https://github.com/Jalle19/satip-axe/assets/666520/14bfbf1f-90a0-4db3-b8e5-1340e44f2ec9">

**Comment by Jalle19** [comment]
That is normal, the tuners will wake up when you try to use them.

**Comment by Jalle19** [comment]
Closing this, not clear if there is any actual issue
