### ISSUE TITLE
HW descr.......

### ISSUE THREAD

**Issue by zildan** [Jalle19/satip-axe#85]
See in attachment, you can implement csa hardware, we still find sources on the net...
[hwdescr.zip](https://github.com/Jalle19/satip-axe/files/15093582/hwdescr.zip)

**Comment by Jalle19** [comment]
If hardware-accelerated DVB-CSA decryption is to be implemented, it needs to be done in minisatip itself. This project is just for the firmware that enables minisatip to run on the supported devices.

I don't think anyone is motivated enough to work on this, and it's not clear that the code you provided is suitable for this particular set of hardware.
