### ISSUE TITLE
Changing root password not possible?

### ISSUE THREAD

**Issue by dicer** [Jalle19/satip-axe#86]
I'm trying to change the root password (or disable password login in dropbear), but I can't figure out how.

I change the password with `passwd` and it works as expected. After a reboot the passwd file gets reset though and the password is `satip` again.

Is there a way I'm missing? Or should I just compile with a custom `fs-add/etc/passwd` and/or `fs-add/etc/init.d/dropbear`?

**Comment by Jalle19** [comment]
I think compiling with a custom etc/passwd is the way to go, yes.
