### ISSUE TITLE
CentOS Repo link is broken

### ISSUE THREAD

**Issue by makabar** [Jalle19/satip-axe#87]
0.651 Loaded plugins: fastestmirror, ovl
1.404 Determining fastest mirrors
1.466 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
1.466 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"

**Comment by Jalle19** [comment]
Crap, guess this is the end of the line. Will have to move to a different build system.

**Comment by makabar** [comment]
Works, thank You
